CREATE TABLE IF NOT EXISTS "Sessions" (
	"Id"			INTEGER NOT NULL UNIQUE,
	"Description"	TEXT,
	"Start"			TEXT NOT NULL,
	"End"			TEXT,
	PRIMARY KEY("Id")
);

CREATE TABLE IF NOT EXISTS "Goals" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Description"	TEXT,
	"Duration"	TEXT NOT NULL,
	"IsDone"	INTEGER,
	PRIMARY KEY("Id")
);